<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Especialidades_producto extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Especialidades_producto_model');
    }
}
