<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Producto extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Producto_model');
    } 

    /*
     * Listing of productos
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('producto/index?');
        $config['total_rows'] = $this->Producto_model->get_all_productos_count();
        $this->pagination->initialize($config);

        $data['productos'] = $this->Producto_model->get_all_productos($params);
        
        $data['_view'] = 'producto/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new producto
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required');
		$this->form_validation->set_rules('descripcion','Descripcion','required');
		$this->form_validation->set_rules('precio_unitario','Precio Unitario','required|numeric|greater_than[0]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
				'descripcion' => $this->input->post('descripcion'),
				'precio_unitario' => $this->input->post('precio_unitario'),
            );
            
            $producto_id = $this->Producto_model->add_producto($params);
            redirect('producto/index');
        }
        else
        {            
            $data['_view'] = 'producto/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a producto
     */
    function edit($id_producto)
    {   
        // check if the producto exists before trying to edit it
        $data['producto'] = $this->Producto_model->get_producto($id_producto);
        
        if(isset($data['producto']['id_producto']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required');
			$this->form_validation->set_rules('descripcion','Descripcion','required');
			$this->form_validation->set_rules('precio_unitario','Precio Unitario','required|numeric|greater_than[0]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
					'descripcion' => $this->input->post('descripcion'),
					'precio_unitario' => $this->input->post('precio_unitario'),
                );

                $this->Producto_model->update_producto($id_producto,$params);            
                redirect('producto/index');
            }
            else
            {
                $data['_view'] = 'producto/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The producto you are trying to edit does not exist.');
    } 

    /*
     * Deleting producto
     */
    function remove($id_producto)
    {
        $producto = $this->Producto_model->get_producto($id_producto);

        // check if the producto exists before trying to delete it
        if(isset($producto['id_producto']))
        {
            $this->Producto_model->delete_producto($id_producto);
            redirect('producto/index');
        }
        else
            show_error('The producto you are trying to delete does not exist.');
    }
    
}
