<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Especialidades_producto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get especialidades_producto by id_especialidad_producto
     */
    function get_especialidades_producto($id_especialidad_producto)
    {
        return $this->db->get_where('especialidades_productos',array('id_especialidad_producto'=>$id_especialidad_producto))->row_array();
    }
        
    /*
     * Get all especialidades_productos
     */
    function get_all_especialidades_productos()
    {
        $this->db->order_by('id_especialidad_producto', 'desc');
        return $this->db->get('especialidades_productos')->result_array();
    }
        
    /*
     * function to add new especialidades_producto
     */
    function add_especialidades_producto($params)
    {
        $this->db->insert('especialidades_productos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update especialidades_producto
     */
    function update_especialidades_producto($id_especialidad_producto,$params)
    {
        $this->db->where('id_especialidad_producto',$id_especialidad_producto);
        return $this->db->update('especialidades_productos',$params);
    }
    
    /*
     * function to delete especialidades_producto
     */
    function delete_especialidades_producto($id_especialidad_producto)
    {
        return $this->db->delete('especialidades_productos',array('id_especialidad_producto'=>$id_especialidad_producto));
    }
}
