<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Producto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get producto by id_producto
     */
    function get_producto($id_producto)
    {
        return $this->db->get_where('productos',array('id_producto'=>$id_producto))->row_array();
    }
    
    /*
     * Get all productos count
     */
    function get_all_productos_count()
    {
        $this->db->from('productos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all productos
     */
    function get_all_productos($params = array())
    {
        $this->db->order_by('id_producto', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('productos')->result_array();
    }
        
    /*
     * function to add new producto
     */
    function add_producto($params)
    {
        $this->db->insert('productos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update producto
     */
    function update_producto($id_producto,$params)
    {
        $this->db->where('id_producto',$id_producto);
        return $this->db->update('productos',$params);
    }
    
    /*
     * function to delete producto
     */
    function delete_producto($id_producto)
    {
        return $this->db->delete('productos',array('id_producto'=>$id_producto));
    }
}
