<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Turno_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get turno by id_turno
     */
    function get_turno($id_turno)
    {
        return $this->db->get_where('turnos',array('id_turno'=>$id_turno))->row_array();
    }
    
    /*
     * Get all turnos count
     */
    function get_all_turnos_count()
    {
        $this->db->from('turnos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all turnos
     */
    function get_all_turnos($params = array())
    {
        $this->db->order_by('id_turno', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('turnos')->result_array();
    }
        
    /*
     * function to add new turno
     */
    function add_turno($params)
    {
        $this->db->insert('turnos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update turno
     */
    function update_turno($id_turno,$params)
    {
        $this->db->where('id_turno',$id_turno);
        return $this->db->update('turnos',$params);
    }
    
    /*
     * function to delete turno
     */
    function delete_turno($id_turno)
    {
        return $this->db->delete('turnos',array('id_turno'=>$id_turno));
    }
}
