<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Turnos_producto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get turnos_producto by id_turno_producto
     */
    function get_turnos_producto($id_turno_producto)
    {
        return $this->db->get_where('turnos_productos',array('id_turno_producto'=>$id_turno_producto))->row_array();
    }
        
    /*
     * Get all turnos_productos
     */
    function get_all_turnos_productos()
    {
        $this->db->order_by('id_turno_producto', 'desc');
        return $this->db->get('turnos_productos')->result_array();
    }
        
    /*
     * function to add new turnos_producto
     */
    function add_turnos_producto($params)
    {
        $this->db->insert('turnos_productos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update turnos_producto
     */
    function update_turnos_producto($id_turno_producto,$params)
    {
        $this->db->where('id_turno_producto',$id_turno_producto);
        return $this->db->update('turnos_productos',$params);
    }
    
    /*
     * function to delete turnos_producto
     */
    function delete_turnos_producto($id_turno_producto)
    {
        return $this->db->delete('turnos_productos',array('id_turno_producto'=>$id_turno_producto));
    }
}
